### ISSUE TITLE
Package overrides "bracket-matcher" settings

### ISSUE THREAD

**Issue by Sogomn** [zargony/atom-language-rust#121]
I have set my bracket matcher package to only complete `{}` brackets and it works fine. However, when editing Rust files, it completes every bracket which is in the default settings. This does not occur when this package is disabled or when launching Atom in safe mode.

**Comment by zargony** [comment]
This sounds similar to an issue with tab length setting that was nagging everybody in #93. It seems that Atom first merges the default settings with package settings and user settings and then chooses editor behavior by looking at the language specific settings, falling back to global settings. This results in language specific package settings overriding user specific global settings. I'm unsure whether this is a bug or intended by Atom (since for most settings this behavior could make sense).

So unfortunately, there's not much we can do about this. You could try to start a discussion with Atom people to see what they think about it. As a workaround, you could try to add rust specific bracket matcher settings in your user settings which should override the settings of language-rust.

**Comment by Sogomn** [comment]
There's a dirty workaround: In the `config.cson`, add
```cson
".rust.source":
  "bracket-matcher":
    autocompleteCharacters: [
      "{}"
      # Add other bracket pairs as you please
    ]
```
to only match specific brackets.
