### ISSUE TITLE
Adding more types to parser

### ISSUE THREAD

**Issue by nathansizemore** [zargony/atom-language-rust#19]
It would be nice if types provided in the std crate were all able to be highlighted, such as Arc, Mutex, Rc, Sender, Receiver, etc...

It's especially helpful when declaring and passing variables that are something like, `Arc<Mutex<Vec<String>>>`

I'd be happy to submit a pull request with the stuff in there, but I didn't know if there was a reason, other than there are a vast number of them, that they were not included and wanted to check if such a pull request would be welcomed before doing it...

**Comment by bombless** [comment]
(Not everybody like the idea of hardcoding know types.)
(Like https://github.com/rust-lang/kate-config/pull/2#issuecomment-72374470)

**Comment by zargony** [comment]
Actually I removed several of the std traits and types in one of the last updates. That's because matching a type is not as simple as matching its name. `Arc` can be a type from everywhere, not just `std::sync::Arc`. Or you could refer to a type by its full or partial module path - or even worse import it with a different name. Currently the rules only include types and traits that are in the std prelude, i.e. those who are available globally without explicitly importing.
However I'm open to suggestions if people want more std types and traits included.
