### ISSUE TITLE
loading any rust file freezes the atom v0.196 

### ISSUE THREAD

**Issue by AtlasInsight** [zargony/atom-language-rust#29]

**Comment by redefiance** [comment]
The problem seems to lie with this line
```cson
'scopeName': 'source.rust'
```
If I change it to
```cson
'scopeName': 'source.corrode'
```
everything seems to be working fine and I still get syntax highlighting

**Comment by d-rezzer** [comment]
Well, That did indeed seems to work

**Comment by zargony** [comment]
I don't seem to have this issue with Atom 0.198. Is this still an issue?

**Comment by HitomiTenshi** [comment]
This issue still exists, though the real cause is linter-rust. @redefiance's proposed fix does fix the hanging when using linter-rust but that's about it.

To reproduce the issue install:
- linter
- linter-rust

and open up a .rs file, it will make language-rust hang.

This is part of a bigger issue in linter-rust posted here:
https://github.com/AtomLinter/linter-rust/issues/11

**Comment by renkun-ken** [comment]
I still have this problem with Atom 0.198.

**Comment by HitomiTenshi** [comment]
The issue has been resolved in:
https://github.com/AtomLinter/linter-rust/issues/11

language-rust isn't freezing with linter-rust anymore.

**Comment by zargony** [comment]
Great!
