### ISSUE TITLE
left shift operator prevents further syntax highlighting

### ISSUE THREAD

**Issue by kunerd** [zargony/atom-language-rust#32]
The left shift operator `<<` prevents further syntax highlighting except the `mut` keyword.

**Comment by exetwezz** [comment]
Everything is fine
```rust
let x = 1 << 2;
let y = 2;
```
This is normally highlighted.

**Comment by kunerd** [comment]
@exetwezz: You are right, your example is also working for me. I tried to build a minimal (not) working example, but it was mainly the content of one the files from my repository, so here is the link were the problem starts:
https://github.com/kunerd/rpaillier/blob/master/src/bigint_extensions.rs#L39

Adding a `;` after [this line](https://github.com/kunerd/rpaillier/blob/master/src/bigint_extensions.rs#L24) solves the problem.

**Comment by exetwezz** [comment]
@kunerd I only know that this is caused due to incorrect interpreting of `<` ― it is assumed to begin a type hint (e.g. `Vec<u32>`), because if you add `>` somewhere after it, the syntax is highlighted further. Also, this explains why `mut` was highlighted (as well as `usize` [further](https://github.com/kunerd/rpaillier/blob/master/src/bigint_extensions.rs#L66)]).

**Comment by zargony** [comment]
Should be fixed by #48
