### ISSUE TITLE
Need to improve the syntax highlighting in Rust

### ISSUE THREAD

**Issue by aeschli** [zargony/atom-language-rust#68]
_From @D101101 on January 20, 2016 17:1_

Syntax highlighting for Rust works well, but in some places it is clearly not completed yet.
![_2016-01-20_19-25-56](https://cloud.githubusercontent.com/assets/8783865/12456219/d59b9d0e-bfaf-11e5-87d0-4bc0bae63908.png)
![_2016-01-20_20-00-12](https://cloud.githubusercontent.com/assets/8783865/12456383/971635ca-bfb0-11e5-89cd-75d189e8d2b1.png)

_Copied from original issue: Microsoft/vscode#2130_

**Comment by aeschli** [comment]
_From @crumblingstatue on February 3, 2016 15:1_

I also find it confusing that keywords and type names share the same highlighting color.

**Comment by veegee** [comment]
+1

**Comment by nixpulvis** [comment]
:+1:

**Comment by zargony** [comment]
You're talking about several issues at once here. In general, I agree that tokenizing (which leads to syntax highlighting) can be improved for some edge cases. Let's use separate issues for discussing/improving the details, since "highlighting needs to be improved" is a rather generic topic for an issue. As far as I can see, you're mentioning the following problems:

Highlighting of nested generics like `Vec<Vec<u64>>`: This has been fixed in #37.

Keywords and type names share the same highlighting color: This depends on the syntax theme you're using. Some themes use different colors, while unfortunately some themes are using same colors for keywords and types.

`Box`, `BufReader` and `VecDeque` are not highlighted: This is because they're not seen as types. Atom-language-rust currently only detects a few known types. These types are matched by string and were therefore intentionally limited to types in the prelude since these can be used without a namespace prefix. It would be nice to have every type highlighted, and maybe we could add a rule to match any type statement. But however, that would lead to the problem that arbitrary type names would be highlighted because atom-language-rust cannot verify if a type actually exists or not. I'm not sure if that would be desirable, but let's open a dedicated issue for this if you think so.

Variable identifier highlighted as type (`let str: &str = ...`): There seems to be a bug that causes variable names to be tokenized as a type if you name your variable like a core/std type (e.g. also happens with `let i8: i8 = 8;`).

**Comment by zargony** [comment]
Closing this in favor of separate issues
