### ISSUE TITLE
Lifetimes are treated as a char incorrectly

### ISSUE THREAD

**Issue by wycats** [zargony/atom-language-rust#8]
``` rs
fn foo<'' // typing a single `'` produces a second `'` incorrectly
```

**Comment by bombless** [comment]
I can fix it by deleting one line of bracket-matcher, but I cannot find a way to add an option for bracket-matcher, the callback hell is too complex for me to understand :D.

Also given the name here I don't understand why bracket-matcher does this, is it handling some behavior inside Atom?
```
Highlight the matching bracket for the `(){}[]` character under the cursor. Move the cursor to the matching bracket with `ctrl-m`. (91297 downloads, 74 stars)
```

Maybe I should open an issue on bracket-matcher suggesting adding the desired option, but I'm not sure.

**Comment by zargony** [comment]
Since Atom's bracket-matcher can be configured now, I added a configuration that excludes single quotes from being autocompleted. This fixes the annoying autocompletion of a second single quote whenever you want to type a lifetime parameter. However this unfortunately completely disables autocompletion for single quotes, i.e. also for character literals where it was actually useful.
I guess this is still better than before. Feedback welcome.
