### ISSUE TITLE
Tab Length setting is not respected

### ISSUE THREAD

**Issue by chpio** [zargony/atom-language-rust#88]
hi,

my "Tab Length" setting is set to 2 (the default), but 4 spaces are used in the source code.

**Comment by mees-** [comment]
I am having the same issue

**Comment by zargony** [comment]
Actually, this is not a bug but by design. The language-rust package sets editor settings that conform to the [Rust style guide](https://doc.rust-lang.org/1.12.0/style/style/whitespace.html). If you really want different settings, you can override them in the package settings.

There's a discussion in #93 where we'll hopefully find out if most people like to keep this behavior or if we should change it.
